### PR TITLE
#158422690 User signup and signin pages.

### PR DESCRIPTION
**Pull request by rethes**
1. What does this PR do?
Sets up Sign up and Sign in pages

2. Description of Task to be completed?
Has the following pages:
Sign up 
Sign in 
Driver dashboard 
Driver profile and edit profile
Passenger dashboard
Passenger profile and edit profile

3. What are the relevant pivotal tracker stories?
#158422690 User signup and sign in pages.

4. Screenshots
User registers
image
Or User signs in
image
A user(passenger) is directed to the dashboard
image
A user(passenger) can view their profile page
image
A user(passenger) can edit their profile page
image
A user(driver) is directed to the dashboard
image
A user(driver) can view their profile page
image
A user(driver) can edit their profile page
image

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
Consider having screenshots of how your pages are rendered on the browser. This way, we can get a glimpse of your flow of thought.

**Comment by Xerrex** [comment]
Kindly share a link to your github page.

**Comment by JoshuaOndieki** [comment]
I suggest you remove the password field in the profiles. Make it a blank input field instead of the actual password label

**Comment by JoshuaOndieki** [comment]
Good work with the color scheme and layout consistency 👏👏

**Comment by xcixor** [comment]
I like the color scheme, and great consistency

**Pull request merged**
